[platformio]
src_dir = .

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_port = COM7

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_port = COM8
